#!/bin/bash
#PBS -l procs=64
#PBS -l walltime=12:00:00
#PBS -l mem=60GB
#PBS -N exoabc
#PBS -M danfm@nyu.edu
#PBS -j oe

module purge
export PATH="$HOME/miniconda3/bin:$PATH"
module load mvapich2/intel/2.0rc1

export OMP_NUM_THREADS=1

export EXOABC_DATA=$SCRATCH/exoabc/data

SRCDIR=$HOME/projects/exoabc
export PATH="$SRCDIR:$PATH"

RUNDIR=$SCRATCH/exoabc/demo/${PBS_JOBID/.*}
mkdir -p $RUNDIR

cd $RUNDIR
mpiexec -np $PBS_NP python $SRCDIR/demo.py

